name: React to Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Node.js Kurulumu
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bağımlılıkları Yükle
        run: npm install

      - name: Web Build Al
        run: npm run build

      - name: Capacitor ile Android'e Çevir
        run: |
          npm install @capacitor/cli @capacitor/core @capacitor/android
          npx cap init M3UFLIX com.mooncrown.m3uflix --web-dir dist
          npx cap add android
          npx cap copy android

      - name: Java ve Android SDK Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: APK Derle (Gradle)
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: APK Dosyasını Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: m3uflix-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
