name: M3U Playlist Otomatik Güncelleyici

on:
  schedule:
    # Her gün gece 00:00'da çalışır
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Manuel olarak çalıştırma butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          pip install requests

      - name: M3U Birleştirme Scriptini Çalıştır
        run: |
          # Burada ana python scriptini çağırıyoruz
          python combine_m3u.py

      - name: Değişiklikleri Kaydet ve Pushla
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Oto-Güncelleme: $(date +'%d-%m-%Y %H:%M')" || exit 0
          git push
